In [3]:
print("pandas library is one of the most important library for data analysis")

pandas library is one of the most important library for data analysis

In [4]:
import pandas as pd

In [6]:
firstDataFrame=pd.DataFrame({'col1':[1,2],'col2':[3,4]});

In [7]:
firstDataFrame

   col1  col2
0     1     3
1     2     4

In [13]:
print("you can also create a Dataframe using values from numpy array, that will discuss later, But for now let us see how to create random array through numpy")

you can also create a Dataframe using values from numpy array, that will discuss later, But for now let us see how to create random array through numpy

In [10]:
import numpy as np

In [11]:
m=np.random.randint(low=8,high=64,size=(6,5))

In [12]:
m

array([[48, 47, 61, 31, 22],
       [53, 22, 16, 32, 45],
       [38, 12, 53, 27, 59],
       [49, 34, 57, 18, 33],
       [54, 10, 54, 18, 36],
       [29, 48, 24, 26, 34]])

In [14]:
print("Lets use these above array to create a dataFrame")

Lets use these above array to create a dataFrame

In [19]:
second_DataFrame=pd.DataFrame(m,columns=["Ae",'height','weight','RBS','FBS'])

In [20]:
second_DataFrame

   Ae  height  weight  RBS  FBS
0  48      47      61   31   22
1  53      22      16   32   45
2  38      12      53   27   59
3  49      34      57   18   33
4  54      10      54   18   36
5  29      48      24   26   34

In [ ]:
#